export const INITIAL_PRODUCTS = [
  {
    id: 'hw-024',
    name: 'Track Ripper',
    edition: 'Silver',
    series: 'HW Starting Grid',
    color: 'Silver',
    hw_num: 24,
    sort_order: 24,
    category: 'HW Starting Grid',
    price: 249,
    stock: 12,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10590/th.jpg',
    description: 'Hot Wheels HW Starting Grid series Track Ripper die-cast racer in sleek Silver edition. Official collector HW# 24.',
    created_at: '2026-01-01T00:00:24Z'
  },
  {
    id: 'hw-031',
    name: 'LA Leibre',
    edition: 'White',
    series: 'HW Dream Garage',
    color: 'White',
    hw_num: 31,
    sort_order: 31,
    category: 'HW Dream Garage',
    price: 249,
    stock: 10,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10617/th.jpg',
    description: 'Hot Wheels HW Dream Garage series LA Leibre die-cast concept sports car in crisp White edition. Official collector HW# 31.',
    created_at: '2026-01-01T00:00:31Z'
  },
  {
    id: 'hw-035',
    name: 'Wattzup',
    edition: 'Gold',
    series: 'HW EV',
    color: 'Gold',
    hw_num: 35,
    sort_order: 35,
    category: 'HW EV',
    price: 299,
    stock: 8,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10602/th.jpg',
    description: 'Hot Wheels HW EV series Wattzup electric hypercar in eye-catching metallic Gold edition. Official collector HW# 35.',
    created_at: '2026-01-01T00:00:35Z'
  },
  {
    id: 'hw-039',
    name: 'Roller Toaster',
    edition: 'Pink',
    series: 'Experimotors',
    color: 'Pink',
    hw_num: 39,
    sort_order: 39,
    category: 'Experimotors',
    price: 249,
    stock: 14,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10591/th.jpg',
    description: 'Hot Wheels Experimotors series Roller Toaster fan-favorite novelty racer in bright Pink edition. Official collector HW# 39.',
    created_at: '2026-01-01T00:00:39Z'
  },
  {
    id: 'hw-041',
    name: 'Ferrari SF90 Stradale',
    edition: 'Black',
    series: 'Ferrari',
    color: 'Black',
    hw_num: 41,
    sort_order: 41,
    category: 'Ferrari',
    price: 499,
    stock: 6,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10610/th.jpg',
    description: 'Hot Wheels Ferrari series Ferrari SF90 Stradale flagship hybrid supercar casting in gloss Black edition. Official collector HW# 41.',
    created_at: '2026-01-01T00:00:41Z'
  },
  {
    id: 'hw-046',
    name: 'Purple Passion',
    edition: 'Purple',
    series: 'HW Fan Driven',
    color: 'Purple',
    hw_num: 46,
    sort_order: 46,
    category: 'HW Fan Driven',
    price: 299,
    stock: 10,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10594/th.jpg',
    description: 'Hot Wheels HW Fan Driven series Purple Passion iconic custom lead sled cruiser in signature deep Purple. Official collector HW# 46.',
    created_at: '2026-01-01T00:00:46Z'
  },
  {
    id: 'hw-048',
    name: 'Monster High Ghoul Mobile',
    edition: 'Black',
    series: 'Mattel',
    color: 'Black',
    hw_num: 48,
    sort_order: 48,
    category: 'Mattel',
    price: 299,
    stock: 10,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10592/th.jpg',
    description: 'Hot Wheels Mattel series Monster High Ghoul Mobile spooky crossover collectible die-cast in Black edition. Official collector HW# 48.',
    created_at: '2026-01-01T00:00:48Z'
  },
  {
    id: 'hw-053',
    name: "'69 Chevelle",
    edition: 'Green',
    series: 'X-Raycers',
    color: 'Green',
    hw_num: 53,
    sort_order: 53,
    category: 'X-Raycers',
    price: 249,
    stock: 11,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10607/th.jpg',
    description: "Hot Wheels X-Raycers series '69 Chevelle classic American muscle car with tinted translucent Green body. Official collector HW# 53.",
    created_at: '2026-01-01T00:00:53Z'
  },
  {
    id: 'hw-055',
    name: 'Dessert Drifter',
    edition: 'Orange',
    series: 'Sweet Rides',
    color: 'Orange',
    hw_num: 55,
    sort_order: 55,
    category: 'Sweet Rides',
    price: 249,
    stock: 15,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10597/th.jpg',
    description: 'Hot Wheels Sweet Rides series Dessert Drifter sweet pastry-inspired novelty racer in zesty Orange edition. Official collector HW# 55.',
    created_at: '2026-01-01T00:00:55Z'
  },
  {
    id: 'hw-057',
    name: 'Raijin Express',
    edition: 'Black',
    series: 'HW Heavyweights',
    color: 'Black',
    hw_num: 57,
    sort_order: 57,
    category: 'HW Heavyweights',
    price: 349,
    stock: 9,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10604/th.jpg',
    description: 'Hot Wheels HW Heavyweights series Raijin Express authentic Japanese Dekotora decorated truck in Black edition. Official collector HW# 57.',
    created_at: '2026-01-01T00:00:57Z'
  },
  {
    id: 'hw-066',
    name: "'17 Audi RS 6 Avant",
    edition: 'Metalflake Champagne',
    series: 'HW Euro',
    color: 'Metalflake Champagne',
    hw_num: 66,
    sort_order: 66,
    category: 'HW Euro',
    price: 349,
    stock: 8,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10612/th.jpg',
    description: "Hot Wheels HW Euro series '17 Audi RS 6 Avant twin-turbo luxury sport wagon in premium Metalflake Champagne. Official collector HW# 66.",
    created_at: '2026-01-01T00:00:66Z'
  },
  {
    id: 'hw-071',
    name: 'Austin Mini Cooper S',
    edition: 'Red',
    series: 'Then and Now',
    color: 'Red',
    hw_num: 71,
    sort_order: 71,
    category: 'Then and Now',
    price: 299,
    stock: 12,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10611/th.jpg',
    description: 'Hot Wheels Then and Now series Austin Mini Cooper S historic British rally champion in classic Red edition. Official collector HW# 71.',
    created_at: '2026-01-01T00:00:71Z'
  },
  {
    id: 'hw-086',
    name: 'VW ID Buzz Bomb',
    edition: 'Blue',
    series: 'HW Euro',
    color: 'Blue',
    hw_num: 86,
    sort_order: 86,
    category: 'HW Euro',
    price: 299,
    stock: 10,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10608/th.jpg',
    description: 'Hot Wheels HW Euro series VW ID Buzz Bomb futuristic electric microbus custom in electric Blue edition. Official collector HW# 86.',
    created_at: '2026-01-01T00:00:86Z'
  },
  {
    id: 'hw-089',
    name: '1985 Honda CR-X',
    edition: 'ZAMAC',
    series: 'HW J-Imports',
    color: 'ZAMAC',
    hw_num: 89,
    sort_order: 89,
    category: 'HW J-Imports',
    price: 399,
    stock: 7,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10216/th.jpg',
    description: 'Hot Wheels HW J-Imports series 1985 Honda CR-X in exclusive unpainted raw ZAMAC metal finish with custom racing livery. Official collector HW# 89.',
    created_at: '2026-01-01T00:00:89Z'
  },
  {
    id: 'hw-128',
    name: 'Datsun 620',
    edition: 'Orange',
    series: 'Compact Kings',
    color: 'Orange',
    hw_num: 128,
    sort_order: 128,
    category: 'Compact Kings',
    price: 299,
    stock: 10,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10616/th.jpg',
    description: 'Hot Wheels Compact Kings series Datsun 620 customized vintage Japanese mini-pickup in vibrant Orange edition. Official collector HW# 128.',
    created_at: '2026-01-01T00:01:28Z'
  },
  {
    id: 'hw-131',
    name: 'Fiat Beast of Turin',
    edition: 'ZAMAC',
    series: 'Drop Tops',
    color: 'ZAMAC',
    hw_num: 131,
    sort_order: 131,
    category: 'Drop Tops',
    price: 399,
    stock: 6,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10752/th.jpg',
    description: 'Hot Wheels Drop Tops series Fiat Beast of Turin legendary 28.5L land-speed record holder in unpainted ZAMAC edition. Official collector HW# 131.',
    created_at: '2026-01-01T00:01:31Z'
  },
  {
    id: 'hw-145',
    name: 'El Segundo Rallye',
    edition: 'Flat Black',
    series: 'HW Dirt',
    color: 'Flat Black',
    hw_num: 145,
    sort_order: 145,
    category: 'HW Dirt',
    price: 249,
    stock: 11,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10596/th.jpg',
    description: 'Hot Wheels HW Dirt series El Segundo Rallye rally-raid desert racer in aggressive Flat Black edition. Official collector HW# 145.',
    created_at: '2026-01-01T00:01:45Z'
  },
  {
    id: 'hw-154',
    name: 'Kick Sauber F1 Team',
    edition: 'Black',
    series: 'Formula 1',
    color: 'Black',
    hw_num: 154,
    sort_order: 154,
    category: 'Formula 1',
    price: 499,
    stock: 5,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10614/th.jpg',
    description: 'Hot Wheels Formula 1 series Kick Sauber F1 Team official licensed Grand Prix open-wheel race car in Black livery. Official collector HW# 154.',
    created_at: '2026-01-01T00:01:54Z'
  },
  {
    id: 'hw-158',
    name: 'Mach Speeder',
    edition: 'Maroon',
    series: 'Exoticars',
    color: 'Maroon',
    hw_num: 158,
    sort_order: 158,
    category: 'Exoticars',
    price: 249,
    stock: 13,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10593/th.jpg',
    description: 'Hot Wheels Exoticars series Mach Speeder aerodynamic concept hypercar in rich metallic Maroon edition. Official collector HW# 158.',
    created_at: '2026-01-01T00:01:58Z'
  },
  {
    id: 'hw-160-spec',
    name: 'Lotus Sport Elise',
    edition: 'Spectraflame Orange',
    series: 'Compact Kings',
    color: 'Spectraflame Orange',
    hw_num: 160,
    sort_order: 160,
    category: 'Compact Kings',
    price: 449,
    stock: 5,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10220/th.jpg',
    description: 'Hot Wheels Compact Kings series Lotus Sport Elise track weapon in brilliant collector Spectraflame Orange finish. Official collector HW# 160.',
    created_at: '2026-01-01T00:02:00Z'
  },
  {
    id: 'hw-160-ora',
    name: 'Lotus Sport Elise',
    edition: 'Orange',
    series: 'Compact Kings',
    color: 'Orange',
    hw_num: 160,
    sort_order: 160.1,
    category: 'Compact Kings',
    price: 299,
    stock: 9,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10620/th.jpg',
    description: 'Hot Wheels Compact Kings series Lotus Sport Elise lightweight British sports car in vibrant gloss Orange edition. Official collector HW# 160.',
    created_at: '2026-01-01T00:02:01Z'
  },
  {
    id: 'hw-161',
    name: "'70 Ford Escort RS1600",
    edition: 'Brown',
    series: 'HW Dirt',
    color: 'Brown',
    hw_num: 161,
    sort_order: 161,
    category: 'HW Dirt',
    price: 299,
    stock: 8,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10619/th.jpg',
    description: "Hot Wheels HW Dirt series '70 Ford Escort RS1600 World Rally Championship icon in earthy Brown edition. Official collector HW# 161.",
    created_at: '2026-01-01T00:02:05Z'
  },
  {
    id: 'hw-162',
    name: 'Total Disposal',
    edition: 'Orange',
    series: 'HW Heavyweights',
    color: 'Orange',
    hw_num: 162,
    sort_order: 162,
    category: 'HW Heavyweights',
    price: 249,
    stock: 12,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10605/th.jpg',
    description: 'Hot Wheels HW Heavyweights series Total Disposal industrial waste and transport hauler in Orange edition. Official collector HW# 162.',
    created_at: '2026-01-01T00:02:10Z'
  },
  {
    id: 'hw-163',
    name: 'Cadillac CelestIQ',
    edition: 'Metalflake Blue',
    series: 'HW EV',
    color: 'Metalflake Blue',
    hw_num: 163,
    sort_order: 163,
    category: 'HW EV',
    price: 349,
    stock: 9,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10595/th.jpg',
    description: 'Hot Wheels HW EV series Cadillac CelestIQ bespoke electric sedan in shimmering Metalflake Blue. Official collector HW# 163.',
    created_at: '2026-01-01T00:02:15Z'
  },
  {
    id: 'hw-165',
    name: 'Gone Mad',
    edition: 'Metalflake Copper',
    series: 'Wagons Familiales',
    color: 'Metalflake Copper',
    hw_num: 165,
    sort_order: 165,
    category: 'Wagons Familiales',
    price: 249,
    stock: 11,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10601/th.jpg',
    description: 'Hot Wheels Wagons Familiales series Gone Mad classic hot rod station wagon in sparkling Metalflake Copper. Official collector HW# 165.',
    created_at: '2026-01-01T00:02:20Z'
  },
  {
    id: 'hw-166',
    name: 'Twin Tags',
    edition: 'Red',
    series: 'Experimotors',
    color: 'Red',
    hw_num: 166,
    sort_order: 166,
    category: 'Experimotors',
    price: 249,
    stock: 14,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10603/th.jpg',
    description: 'Hot Wheels Experimotors series Twin Tags innovative moving-parts die-cast concept in bold Red edition. Official collector HW# 166.',
    created_at: '2026-01-01T00:02:25Z'
  },
  {
    id: 'hw-167',
    name: 'Head Gasket',
    edition: 'Orange and Green',
    series: 'HW All Drivers Welcome',
    color: 'Orange and Green',
    hw_num: 167,
    sort_order: 167,
    category: 'HW All Drivers Welcome',
    price: 249,
    stock: 10,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10598/th.jpg',
    description: 'Hot Wheels HW All Drivers Welcome series Head Gasket exposed engine rat rod in dynamic Orange and Green scheme. Official collector HW# 167.',
    created_at: '2026-01-01T00:02:30Z'
  },
  {
    id: 'hw-168',
    name: 'Mailed IT!',
    edition: 'Blue',
    series: 'Team Wheels',
    color: 'Blue',
    hw_num: 168,
    sort_order: 168,
    category: 'Team Wheels',
    price: 249,
    stock: 13,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10599/th.jpg',
    description: 'Hot Wheels Team Wheels series Mailed IT! high-speed parcel express van in Royal Blue edition. Official collector HW# 168.',
    created_at: '2026-01-01T00:02:35Z'
  },
  {
    id: 'hw-169',
    name: 'Super Twin Mill',
    edition: 'White',
    series: "Hot Wheels Let's Race",
    color: 'White',
    hw_num: 169,
    sort_order: 169,
    category: "Hot Wheels Let's Race",
    price: 299,
    stock: 10,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10600/th.jpg',
    description: "Hot Wheels Let's Race series Super Twin Mill legendary dual-supercharged custom in pure White edition. Official collector HW# 169.",
    created_at: '2026-01-01T00:02:40Z'
  },
  {
    id: 'hw-170',
    name: "'64 Lincoln Continental",
    edition: 'Orange',
    series: 'Cool Classics',
    color: 'Orange',
    hw_num: 170,
    sort_order: 170,
    category: 'Cool Classics',
    price: 349,
    stock: 7,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10606/th.jpg',
    description: "Hot Wheels Cool Classics series '64 Lincoln Continental iconic lowrider luxury cruiser in vibrant Orange finish. Official collector HW# 170.",
    created_at: '2026-01-01T00:02:45Z'
  },
  {
    id: 'hw-171',
    name: '1983 Porsche 928S',
    edition: 'Black',
    series: 'HW Euro',
    color: 'Black',
    hw_num: 171,
    sort_order: 171,
    category: 'HW Euro',
    price: 349,
    stock: 8,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10615/th.jpg',
    description: 'Hot Wheels HW Euro series 1983 Porsche 928S pop-up headlight V8 grand touring coupe in deep Black finish. Official collector HW# 171.',
    created_at: '2026-01-01T00:02:50Z'
  },
  {
    id: 'hw-172',
    name: 'Tooned Volkswagen Golf MK1',
    edition: 'White',
    series: 'Tooned',
    color: 'White',
    hw_num: 172,
    sort_order: 172,
    category: 'Tooned',
    price: 249,
    stock: 12,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10618/th.jpg',
    description: 'Hot Wheels Tooned series Volkswagen Golf MK1 cartoonish custom hatchback with oversized engine in White edition. Official collector HW# 172.',
    created_at: '2026-01-01T00:02:55Z'
  },
  {
    id: 'hw-181',
    name: 'Mercedes-Benz CLA HW',
    edition: 'Blue',
    series: 'HW Euro',
    color: 'Blue',
    hw_num: 181,
    sort_order: 181,
    category: 'HW Euro',
    price: 349,
    stock: 9,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10613/th.jpg',
    description: 'Hot Wheels HW Euro series Mercedes-Benz CLA HW aerodynamic four-door sports sedan in metallic Blue edition. Official collector HW# 181.',
    created_at: '2026-01-01T00:03:00Z'
  },
  {
    id: 'hw-191',
    name: "'65 Mercury Comet Cyclone",
    edition: 'Red',
    series: 'Drag Racers',
    color: 'Red',
    hw_num: 191,
    sort_order: 191,
    category: 'Drag Racers',
    price: 349,
    stock: 7,
    in_stock: true,
    display_section: 'grid',
    image_url: 'https://164custom.com/images/HW/10609/th.jpg',
    description: "Hot Wheels Drag Racers series '65 Mercury Comet Cyclone high-compression drag strip beast in fiery Red edition. Official collector HW# 191.",
    created_at: '2026-01-01T00:03:05Z'
  }
]
